access dialogues via handler
valory-xyz/open-aea pull request #151
Opened 2022-05-24 15:08 UTC by Karrenbelt

## Proposed changes

Make dialogues accessible via their handler

## Fixes

If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to agents-aea?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [ ] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [ ] I am making a pull request against the `develop` branch (left side). Also you should start your branch off our `develop`.
- [ ] Lint and unit tests pass locally with my changes and CI passes too
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that code coverage does not decrease.
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-05-25 09:20 UTC, DavidMinarsch commented on aea/skills/base.py
> +        attribute = cast(PublicId, self.SUPPORTED_PROTOCOL).name + "_dialogues"
On consideration, this doesn't make much sense. The attribute is user defined via the skill.yaml.

2022-05-25 09:20 UTC, DavidMinarsch commented on aea/skills/base.py
> +        attribute = cast(PublicId, self.SUPPORTED_PROTOCOL).name + "_dialogues"
Will keep open but won't merge for now as a result.

2022-05-26 07:33 UTC, DavidMinarsch requested changes

2022-05-26 07:33 UTC, DavidMinarsch commented on aea/skills/base.py
> +    def protocol_dialogues(self) -> "Dialogues":  # type: ignore # noqa: F821
```suggestion
    def protocol_dialogues(self, attribute: Optional[str] = None) -> "Dialogues":  # type: ignore # noqa: F821
```

2022-05-26 07:33 UTC, DavidMinarsch commented on aea/skills/base.py
> +        attribute = cast(PublicId, self.SUPPORTED_PROTOCOL).name + "_dialogues"
```suggestion
        attribute = cast(PublicId, self.SUPPORTED_PROTOCOL).name + "_dialogues" if attribute is None else attribute
```

2022-05-26 09:05 UTC, angrybayblade commented on aea/skills/base.py
> +    def protocol_dialogues(self) -> "Dialogues":  # type: ignore # noqa: F821
Circular import issue

2022-05-26 09:15 UTC, angrybayblade commented on aea/skills/base.py
> +    def protocol_dialogues(self, attribute: Optional[str] = None):  # type: ignore
> type: ignore

Because of the circular import caused by `Dialogue` class cannot assign a return type to this

2022-05-26 10:32 UTC, DavidMinarsch commented
Currently failing test: tests/test_skills/test_base.py::TestSkillProgrammatic::test_protocol_dialogues

2022-05-26 11:53 UTC, DavidMinarsch approved these changes

2022-05-26 11:54 UTC, merged