[WIP] Add support for service component
valory-xyz/open-aea pull request #161
Opened 2022-05-30 12:27 UTC by angrybayblade

## Proposed changes

Add support for service component and patch `hash all` command to support service hashing

## Types of changes

What types of changes does your code introduce to agents-aea?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [ ] I am making a pull request against the `develop` branch (left side). Also you should start your branch off our `develop`.
- [ ] Lint and unit tests pass locally with my changes and CI passes too
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that code coverage does not decrease.
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

2022-05-30 12:52 UTC, angrybayblade commented on aea/cli/ipfs_hash.py
> +    ] = load_configuration,
To patch the config loader on swarm

2022-05-30 13:53 UTC, DavidMinarsch commented on aea/configurations/loader.py
> +        """Load an agent configuration."""
```suggestion
        """Load a service configuration."""
```

2022-05-30 13:53 UTC, DavidMinarsch requested changes
Please add tests for the new functionality.

2022-06-01 09:11 UTC, 8ball030 approved these changes
LGTM

2022-06-01 09:18 UTC, DavidMinarsch approved these changes

2022-06-01 09:18 UTC, merged