[WIP] Config loader patch
valory-xyz/open-aea pull request #190
Opened 2022-06-16 09:19 UTC by angrybayblade

## Proposed changes

This PR makes config loaders patchable by updating methods which use config loaders to support custom config loader support.

## Types of changes

What types of changes does your code introduce to agents-aea?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [ ] I am making a pull request against the `develop` branch (left side). Also you should start your branch off our `develop`.
- [x] Lint and unit tests pass locally with my changes and CI passes too
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that code coverage does not decrease.
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

2022-06-16 10:25 UTC, angrybayblade reviewed
So I have patched every method which uses the config loaders and might have to load the service config in some way or another so we can overwrite commands as we need on the autonomy package to support service config loading.

2022-06-16 11:06 UTC, dvilelaf approved these changes

2022-06-16 15:41 UTC, DavidMinarsch commented on aea/cli/push_all.py
> +        raise click.ClickException(str(e)) from e
I think it would be better to catch the value error earlier, e.g. wrap lines 72-73? Everything else is handled afaict

2022-06-16 15:42 UTC, DavidMinarsch requested changes
Where are the tests with some mock config ?

2022-06-17 05:16 UTC, angrybayblade commented
> Where are the tests with some mock config ?

We already have the config loader patch tests: https://github.com/valory-xyz/open-aea/blob/0b8d75f5c7a449d8b281936919c086dd28f69962/tests/test_configurations/test_loader.py#L109

2022-06-19 19:17 UTC, DavidMinarsch approved these changes

2022-06-19 19:18 UTC, merged