Docs/ipfs hash tests & fixer script
valory-xyz/open-aea pull request #193
Opened 2022-06-20 16:51 UTC by dvilelaf

## Proposed changes

- Auto-detect ipfs hashes in our docs and fix them
- Test for ipfs hashes in the docs

## Fixes

n/a

## Types of changes

What types of changes does your code introduce to agents-aea?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [x] I am making a pull request against the `develop` branch (left side). Also you should start your branch off our `develop`.
- [x] Lint and unit tests pass locally with my changes and CI passes too
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that code coverage does not decrease.
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

2022-06-20 20:15 UTC, DavidMinarsch requested changes
Remove the svn command too please.

Also don't forget about `aea add`

2022-06-20 20:15 UTC, DavidMinarsch commented on docs/echo_demo.md
> -aea fetch open_aea/my_first_aea:0.1.0 --local
Why are you removing the version?

2022-06-21 16:12 UTC, dvilelaf commented on docs/agent-vs-aea.md
> +First, import the python and application specific libraries. (Get the packages directory from the AEA repository `aea fetch PUBLIC_ID_OR_HASH`.)
These svn commands were not specific to a package but a recommendation on how to get packages, so I just set this to a general command that i saw in other places in the docs.

2022-06-21 19:25 UTC, DavidMinarsch commented on docs/agent-vs-aea.md
> +First, import the python and application specific libraries. (Get the packages directory from the AEA repository `aea fetch PUBLIC_ID_OR_HASH`.)
```suggestion
First, import the python and application specific libraries. (Get the packages directory from the AEA repository `svn export https://github.com/valory-xyz/open-aea.git/trunk/packages`.)
```
It makes no sense here now. If you read the sentence it has no place here as such. The whole guide doesn't make any sense anymore. It needs to be properly fixed.

2022-06-21 19:25 UTC, DavidMinarsch commented on docs/decision-maker-transaction.md
> +First, import the libraries and the set the constant values. (Get the packages directory from the AEA repository `aea fetch PUBLIC_ID_OR_HASH`.)
also doesn't make sense. You can see below it only uses one protocol. The `aea add ..` command could be used. But then it's in an agent project. Need to find another way.

2022-06-21 19:25 UTC, DavidMinarsch commented on docs/echo_demo.md
> +aea fetch fetchai/my_first_aea:0.27.0:QmcmunuEAvaKfLCJsgeqF8M5dKARHixu4otUFVGbEenaCm --remote
```suggestion
aea fetch open_aea/my_first_aea:0.1.0:QmbyFaoHWikC8dHcpdTVboxVnkXX2vMgch4UUXmwCfJhRu --remote
```

2022-06-21 19:25 UTC, DavidMinarsch commented on docs/multiplexer-standalone.md
> +First, import the Python and application specific libraries and set the static variables. (Get the packages directory from the AEA repository `aea fetch PUBLIC_ID_OR_HASH`.)
Same problem as above

2022-06-21 19:25 UTC, DavidMinarsch commented on docs/quickstart.md
> +To load Valory packages please use <a href="https://subversion.apache.org/packages.html" target="_blank">aea fetch</a> to checkout the specific packages;
```suggestion
```
@dvilelaf please read the whole para and then fix.

2022-06-21 19:25 UTC, DavidMinarsch commented on docs/quickstart.md
>  ```bash
```suggestion
```

2022-06-21 19:25 UTC, DavidMinarsch commented on docs/quickstart.md
> +aea fetch PUBLIC_ID_OR_HASH
```suggestion
```

2022-06-21 19:25 UTC, DavidMinarsch commented on docs/quickstart.md
>  ```
```suggestion
```

2022-06-21 19:25 UTC, DavidMinarsch commented on docs/quickstart.md
>  cd my_first_aea
```suggestion
aea fetch open_aea/my_first_aea:0.1.0:QmbyFaoHWikC8dHcpdTVboxVnkXX2vMgch4UUXmwCfJhRu --remote
cd my_first_aea
```

2022-06-21 19:25 UTC, DavidMinarsch commented on docs/quickstart.md
> +aea fetch fetchai/my_first_aea:0.27.0:QmcmunuEAvaKfLCJsgeqF8M5dKARHixu4otUFVGbEenaCm --remote
```suggestion
svn export https://github.com/valory-xyz/open-aea.git/trunk/packages
```
Replacing the single line and not changing the text won't work!

2022-06-21 19:25 UTC, DavidMinarsch commented on docs/decision-maker-transaction.md
> +First, import the libraries and the set the constant values. (Get the packages directory from the AEA repository `aea fetch PUBLIC_ID_OR_HASH`.)
```suggestion
First, import the libraries and the set the constant values. (Get the packages directory from the AEA repository `svn export https://github.com/valory-xyz/open-aea.git/trunk/packages`.)
```

2022-06-21 19:25 UTC, DavidMinarsch commented on tests/test_docs/test_bash_yaml/md_files/bash-quickstart.md
> +```
```suggestion
```

2022-06-21 19:32 UTC, DavidMinarsch commented on docs/http-connection-and-skill.md
> +aea add connection fetchai/http_server:0.22.0:Qmdr2Ajx5BRBJCC6xP8wUNSCMbhStHHZaVgzkoSW6Pvu7S
```suggestion
aea add connection fetchai/http_server:0.22.0:Qmdr2Ajx5BRBJCC6xP8wUNSCMbhStHHZaVgzkoSW6Pvu7S --remote
```

2022-06-21 19:32 UTC, DavidMinarsch commented on docs/ipfs_registry.md
> +`aea add protocol QmWdCAiXpeT1tgrcf8uofKdQ6fLxMH77D5jwgQbbMo41df`
```suggestion
`aea add protocol QmWdCAiXpeT1tgrcf8uofKdQ6fLxMH77D5jwgQbbMo41df --remote`
```

2022-06-21 19:32 UTC, DavidMinarsch commented on docs/ipfs_registry.md
> +`aea add protocol open_aea/signing:1.0.0:QmWdCAiXpeT1tgrcf8uofKdQ6fLxMH77D5jwgQbbMo41df`
```suggestion
`aea add protocol open_aea/signing:1.0.0:QmWdCAiXpeT1tgrcf8uofKdQ6fLxMH77D5jwgQbbMo41df --remote`
```

2022-06-21 19:32 UTC, DavidMinarsch commented on docs/multiplexer-standalone.md
> +First, import the Python and application specific libraries and set the static variables. (Get the packages directory from the AEA repository `aea fetch PUBLIC_ID_OR_HASH`.)
```suggestion
First, import the Python and application specific libraries and set the static variables. (Get the packages directory from the AEA repository `svn export https://github.com/valory-xyz/open-aea.git/trunk/packages`.)
```

2022-06-21 19:32 UTC, DavidMinarsch commented on docs/p2p-connection.md
> +aea add connection valory/p2p_libp2p:0.1.0:QmYW7Q5iFN6RwWmHj7wvjUBZfxu3hJN4KvcTWW1AhdKhki
```suggestion
aea add connection valory/p2p_libp2p:0.1.0:QmYW7Q5iFN6RwWmHj7wvjUBZfxu3hJN4KvcTWW1AhdKhki --remote
```

2022-06-21 19:32 UTC, DavidMinarsch commented on docs/p2p-connection.md
> +aea add connection valory/p2p_libp2p:0.1.0:QmYW7Q5iFN6RwWmHj7wvjUBZfxu3hJN4KvcTWW1AhdKhki
```suggestion
aea add connection valory/p2p_libp2p:0.1.0:QmYW7Q5iFN6RwWmHj7wvjUBZfxu3hJN4KvcTWW1AhdKhki --remote
```

2022-06-21 19:32 UTC, DavidMinarsch commented on docs/quickstart.md
> +aea add connection fetchai/stub:0.21.0:QmektTWmXcjThQd8md8nSYgLapR3Gks3n3WEzwAWQFgc4z
```suggestion
aea add connection fetchai/stub:0.21.0:QmektTWmXcjThQd8md8nSYgLapR3Gks3n3WEzwAWQFgc4z --remote
```

2022-06-21 19:32 UTC, DavidMinarsch commented on docs/quickstart.md
> +aea add skill fetchai/echo:0.19.0:QmReV2qgjE4mkY9n5iwJDoEcv174Sxbjhxo84YZpLyvcR2
```suggestion
aea add skill fetchai/echo:0.19.0:QmReV2qgjE4mkY9n5iwJDoEcv174Sxbjhxo84YZpLyvcR2 --remote
```

2022-06-21 19:32 UTC, DavidMinarsch commented on docs/registry.md
> +aea add skill fetchai/echo:0.19.0:QmReV2qgjE4mkY9n5iwJDoEcv174Sxbjhxo84YZpLyvcR2
```suggestion
aea add skill fetchai/echo:0.19.0:QmReV2qgjE4mkY9n5iwJDoEcv174Sxbjhxo84YZpLyvcR2 --remote
```

2022-06-21 19:32 UTC, DavidMinarsch commented on tests/test_docs/test_bash_yaml/md_files/bash-gym-skill.md
> +aea add skill fetchai/gym:0.20.0:QmdQisuqLhq81NHuas9ALYgP1tw1cZoE3vGueREgG8PgCZ
```suggestion
aea add skill fetchai/gym:0.20.0:QmdQisuqLhq81NHuas9ALYgP1tw1cZoE3vGueREgG8PgCZ --remote
```

2022-06-21 19:32 UTC, DavidMinarsch commented on tests/test_docs/test_bash_yaml/md_files/bash-http-connection-and-skill.md
> +aea add connection fetchai/http_server:0.22.0:Qmdr2Ajx5BRBJCC6xP8wUNSCMbhStHHZaVgzkoSW6Pvu7S
```suggestion
aea add connection fetchai/http_server:0.22.0:Qmdr2Ajx5BRBJCC6xP8wUNSCMbhStHHZaVgzkoSW6Pvu7S --remote
```

2022-06-22 08:40 UTC, merged