Chore/tomte
valory-xyz/open-aea pull request #363
Opened 2022-10-10 16:12 UTC by dvilelaf

## Proposed changes

Adds tomte, our new wrapper for common tooling.

## Fixes

n/a

## Types of changes

What types of changes does your code introduce to agents-aea?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [x] I am making a pull request against the `develop` branch (left side). Also you should start your branch off our `develop`.
- [x] Lint and unit tests pass locally with my changes and CI passes too
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that code coverage does not decrease.
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

2022-10-10 16:13 UTC, dvilelaf commented on Pipfile
> +tomte = {version = "==0.1.3", extras = ["tox", "tests"]}
Linters now come from tomte.

2022-10-10 19:32 UTC, DavidMinarsch commented on tox.ini
>  deps =
As in the `open-autonomy` please split this into deps for framework, tests and packages: https://github.com/valory-xyz/open-autonomy/pull/1411/files#diff-ef2cef9f88b4fe09ca3082140e67f5ad34fb65fb6e228f119d3812261ae51449R13-R30

2022-10-10 19:33 UTC, DavidMinarsch commented on tox.ini
>  deps =
Below we already define envs for `plugins`, `packages` and `framework` so use these imo and then add `tests`

2022-10-10 19:34 UTC, DavidMinarsch commented on tox.ini
>      click==8.0.2
Remove click here, it's already part of `tomte[black]`

2022-10-10 19:34 UTC, DavidMinarsch commented on tox.ini
>      click==8.0.2
see above

2022-10-10 19:39 UTC, DavidMinarsch requested changes

2022-10-10 19:39 UTC, DavidMinarsch commented on tox.ini
>  skipsdist = True
above `hash-check` should be updated to use `open-aea[all]` and `open-aea-cli-ipfs` instead. Then also directly use  cli rather than via `python -m`

2022-10-10 19:39 UTC, DavidMinarsch commented on tox.ini
> -    protobuf<=3.20.1
You might have to add these in pylint ignore

2022-10-10 19:39 UTC, DavidMinarsch commented on tox.ini
> +    tomte[isort]==0.1.5
This needs to use local installation of open-aea and open-aea-cli-ipfs

2022-10-10 19:39 UTC, DavidMinarsch commented on tox.ini
>  deps =
This whole env needs to be deduplicated; hence why the above recommended split into the three envs, then hopefully, the diff to multi and base is clear

2022-10-11 13:53 UTC, dvilelaf commented on scripts/check_pipfile_and_toxini.py
> +    "open-aea-cli-ipfs": "==1.21.0",
This are not present on the Pipfile of course, so I had to add them here.

2022-10-11 13:57 UTC, dvilelaf commented
Merging main and running formatters has changed +150 files. Also tehre are hundreds of pylint errors, especially wrt fstrings formatting.

2022-10-13 11:28 UTC, closed without merging